export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
};

export const HTTP_MESSAGES = {
  [HTTP_STATUS.OK]: 'Success',
  [HTTP_STATUS.CREATED]: 'Created Successfully',
  [HTTP_STATUS.BAD_REQUEST]: 'Bad Request',
  [HTTP_STATUS.UNAUTHORIZED]: 'Unauthorized Access',
  [HTTP_STATUS.FORBIDDEN]: 'Forbidden Action',
  [HTTP_STATUS.NOT_FOUND]: 'Resource Not Found',
  [HTTP_STATUS.CONFLICT]: 'Conflict Occurred',
  [HTTP_STATUS.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
};
